
package org.example.dictionaryeejaxws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DictionaryWebServiceImplService", targetNamespace = "http://impl.webservice.server.dictionaryeejaxws.example.org/", wsdlLocation = "http://localhost:8080/Dictionary-EE-Jax-Ws-1.0-SNAPSHOT/DictionaryWebServiceImpl?wsdl")
public class DictionaryWebServiceImplService
    extends Service
{

    private final static URL DICTIONARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DICTIONARYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DICTIONARYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.server.dictionaryeejaxws.example.org/", "DictionaryWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Dictionary-EE-Jax-Ws-1.0-SNAPSHOT/DictionaryWebServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DICTIONARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DICTIONARYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DictionaryWebServiceImplService() {
        super(__getWsdlLocation(), DICTIONARYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DictionaryWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DICTIONARYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DictionaryWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DICTIONARYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DictionaryWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DICTIONARYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DictionaryWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DictionaryWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DictionaryWebService
     */
    @WebEndpoint(name = "DictionaryWebServiceImplPort")
    public DictionaryWebService getDictionaryWebServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.server.dictionaryeejaxws.example.org/", "DictionaryWebServiceImplPort"), DictionaryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DictionaryWebService
     */
    @WebEndpoint(name = "DictionaryWebServiceImplPort")
    public DictionaryWebService getDictionaryWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.server.dictionaryeejaxws.example.org/", "DictionaryWebServiceImplPort"), DictionaryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DICTIONARYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DICTIONARYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DICTIONARYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
