
package org.example.dictionaryeejaxws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DictionaryWebService", targetNamespace = "http://api.webservice.server.dictionaryeejaxws.example.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DictionaryWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void createWord(
        @WebParam(name = "arg0", partName = "arg0")
        WordDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void deleteWord(
        @WebParam(name = "arg0", partName = "arg0")
        WordDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void getTranslation(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void updateTranslation(
        @WebParam(name = "arg0", partName = "arg0")
        WordDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.dictionaryeejaxws.server.XmlWords
     */
    @WebMethod
    @WebResult(partName = "return")
    public XmlWords getWords(
        @WebParam(name = "arg0", partName = "arg0")
        DictionaryType arg0);

}
